function render(){syncYears();const rows=filtered();const exp=rows.reduce((s,r)=>s+(Number(r.expense)||0),0);$('#metricExpense').textContent=yen(exp);$('#metricCount').textContent=rows.length;$('#metricReview').textContent=rows.filter(r=>!r.confirmed).length;$('#receiptList').innerHTML=rows.map(r=>{let url='';if(r.imageBlob)url=URL.createObjectURL(r.imageBlob);return `<button class="receipt-card" data-id="${esc(r.id)}" type="button"><div>${url?`<img class="receipt-thumb" src="${url}" alt="">`:'<div class="receipt-thumb" style="display:grid;place-items:center;font-size:25px">🧾</div>'}</div><div class="receipt-main"><div class="receipt-topline"><h3>${esc(r.vendor||'支払先未入力')}</h3><span class="badge ${r.confirmed?'':'review'}">${r.confirmed?'確認済み':'要確認'}</span></div><p class="receipt-meta">${esc(r.date||'日付なし')} ・ ${esc(r.category||'科目なし')} ・ ${esc(r.incomeType||'')}</p><p class="receipt-purpose">${esc(r.purpose||'')}</p></div><div class="receipt-amount"><strong>${yen(r.expense)}</strong><small>支払 ${yen(r.amount)}</small></div></button>`}).join('');$('#emptyState').hidden=rows.length>0;$$('.receipt-card').forEach(b=>b.addEventListener('click',()=>openEdit(b.dataset.id)));renderSummaries(rows)}
function renderSummaries(rows){const cat={};rows.forEach(r=>cat[r.category]=(cat[r.category]||0)+(Number(r.expense)||0));const catEntries=Object.entries(cat).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...catEntries.map(x=>x[1]));$('#categorySummary').innerHTML=catEntries.length?`<table class="summary-table"><tbody>${catEntries.map(([k,v])=>`<tr><td>${esc(k)}<div class="summary-bar"><span style="width:${Math.round(v/max*100)}%"></span></div></td><td>${yen(v)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">データがありません。</p>';const mon={};rows.forEach(r=>{const m=(r.date||'').slice(0,7)||'日付なし';mon[m]=(mon[m]||0)+(Number(r.expense)||0)});const ms=Object.entries(mon).sort((a,b)=>a[0].localeCompare(b[0]));$('#monthSummary').innerHTML=ms.length?`<table class="summary-table"><tbody>${ms.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${yen(v)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">データがありません。</p>'}

function resetForm(){state.editingId=null;state.selectedImage=null;state.selectedImageName='';$('#receiptForm').reset();$('#receiptId').value='';$('#dateInput').value=localToday();$('#businessPctInput').value=100;$('#incomeTypeInput').value='不動産所得';$('#categoryInput').value='雑費';$('#imagePreview').hidden=true;$('#capturePrompt').hidden=false;$('#ocrText').value='';$('#ocrStatus').textContent='ネットなしでも手入力できます';$('#deleteBtn').hidden=true;$('#dialogTitle').textContent='レシートを追加';calcExpense();categoryHint()}
function openAdd(){resetForm();$('#receiptDialog').showModal()}
function openEdit(id){const r=state.records.find(x=>x.id===id);if(!r)return;resetForm();state.editingId=id;$('#receiptId').value=id;$('#dateInput').value=r.date||'';$('#vendorInput').value=r.vendor||'';$('#amountInput').value=r.amount||0;$('#businessPctInput').value=r.businessPct??100;$('#incomeTypeInput').value=r.incomeType||'不動産所得';$('#categoryInput').value=r.category||'雑費';$('#paymentInput').value=r.payment||'現金';$('#purposeInput').value=r.purpose||'';$('#memoInput').value=r.memo||'';$('#ocrText').value=r.ocrText||'';$('#confirmedInput').checked=!!r.confirmed;state.selectedImage=r.imageBlob||null;state.selectedImageName=r.imageName||'';if(r.imageBlob){$('#imagePreview').src=URL.createObjectURL(r.imageBlob);$('#imagePreview').hidden=false;$('#capturePrompt').hidden=true}$('#deleteBtn').hidden=false;$('#dialogTitle').textContent='レシートを編集';calcExpense();categoryHint();$('#receiptDialog').showModal()}
function calcExpense(){const a=Math.max(0,Number($('#amountInput').value)||0),p=Math.min(100,Math.max(0,Number($('#businessPctInput').value)||0));$('#expenseInput').value=Math.round(a*p/100)}
function categoryHint(){const c=$('#categoryInput').value;const map={'雑費':'ほかの主要科目に当てはまらない少額・臨時的な費用の候補。多用せず内容をメモすると確認しやすくなります。','修繕費':'通常の維持・原状回復か、資産価値を高める支出かで扱いが変わることがあります。','修繕積立金':'不動産では支払時にそのまま必要経費にならないケースがあります。管理規約・使途・返還条件などの確認用に分類しておきましょう。','減価償却費':'高額・長期使用する資産は購入年に全額経費ではなく減価償却になる場合があります。','接待交際費':'相手・目的・人数など、事業との関係が分かるメモを残すと確認しやすくなります。'};const h=$('#categoryHint');if(map[c]){h.textContent='確認ポイント：'+map[c];h.style.display='block'}else h.style.display='none'}

async function imageSelected(file){if(!file)return;state.selectedImage=file;state.selectedImageName=file.name||'receipt-image';$('#imagePreview').src=URL.createObjectURL(file);$('#imagePreview').hidden=false;$('#capturePrompt').hidden=true;$('#ocrStatus').textContent='画像を選択しました。OCRまたは手入力で確認してください。'}
async function loadTesseract(){if(window.Tesseract)return;$('#ocrStatus').textContent='OCRエンジンを読み込んでいます…';await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=res;s.onerror=()=>rej(new Error('OCRエンジンを取得できません'));document.head.appendChild(s)})}
function numFrom(s){return Number(String(s).replace(/[¥￥,，\s]/g,'').replace(/[^0-9.-]/g,''))||0}
function extractOCR(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let date='';const dateRx=/(20\d{2})[\/.年-]\s*(\d{1,2})[\/.月-]\s*(\d{1,2})日?/;for(const line of lines){const m=line.match(dateRx);if(m){date=`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;break}}let vendor='';for(const l of lines.slice(0,8)){if(l.length>=2&&!/領収|レシート|receipt|tel|電話|〒|20\d{2}/i.test(l)){vendor=l.replace(/^[*\-\s]+|[*\-\s]+$/g,'');break}}const totalKeys=/合計|総合計|お支払|お買上|現計|税込|total|amount/i;let candidates=[];for(const l of lines){const nums=(l.match(/[¥￥]?\s*\d{1,3}(?:[,，]\d{3})+|[¥￥]\s*\d+|\d+\s*円/g)||[]).map(numFrom).filter(n=>n>0);if(totalKeys.test(l))candidates.push(...nums.map(n=>({n,score:2})));else candidates.push(...nums.map(n=>({n,score:1})))}candidates.sort((a,b)=>b.score-a.score||b.n-a.n);const amount=candidates[0]?.n||0;const cat=suggestCategory(text);return{date,vendor,amount,category:cat}}
function suggestCategory(text){const t=text.toLowerCase();const rules=[['通信費',/携帯|mobile|電話|通信|wifi|wi-fi|internet|インターネット|郵便|切手/],['旅費交通費',/jr|鉄道|電車|バス|タクシ|高速|parking|駐車|航空|ana|jal|交通/],['消耗品費',/文具|ホームセンター|amazon|アマゾン|コピー|トナー|インク|電池|清掃|100円|ダイソー|seria|セリア/],['修繕費',/修理|修繕|交換工事|補修|工事|リフォーム/],['水道光熱費',/電気|ガス|水道|東京電力|tepco/],['損害保険料',/保険|火災保険|地震保険/],['地代家賃',/家賃|賃料|地代/],['管理費',/管理費|管理会社/],['広告宣伝費',/広告|印刷|チラシ|meta|google ads|facebook/],['接待交際費',/居酒屋|レストラン|会食|贈答|手土産/],['新聞図書費',/書店|書籍|新聞|kindle/],['研修費',/講座|セミナー|研修|受講/]];for(const [c,re] of rules)if(re.test(t))return c;return'雑費'}
async function runOCR(){if(!state.selectedImage){toast('先にレシート画像を選んでください');return}try{await loadTesseract();$('#ocrBtn').disabled=true;const worker=await Tesseract.createWorker('jpn+eng',1,{logger:m=>{if(m.status==='recognizing text')$('#ocrStatus').textContent=`文字を読んでいます… ${Math.round((m.progress||0)*100)}%`;else $('#ocrStatus').textContent='OCR準備中…'}});const ret=await worker.recognize(state.selectedImage);await worker.terminate();const text=ret.data.text||'';$('#ocrText').value=text;const x=extractOCR(text);if(x.date)$('#dateInput').value=x.date;if(x.vendor)$('#vendorInput').value=x.vendor;if(x.amount)$('#amountInput').value=x.amount;if(x.category)$('#categoryInput').value=x.category;calcExpense();categoryHint();$('#ocrDetails').open=true;$('#confirmedInput').checked=false;$('#ocrStatus').textContent='候補を入れました。必ず内容を確認してください。';toast('OCR完了：内容を確認してください')}catch(e){console.error(e);$('#ocrStatus').textContent='OCRできませんでした。手入力で登録できます。';toast('OCRに失敗しました')}finally{$('#ocrBtn').disabled=false}}
